### 阿里云 上传文件
POST http://localhost:10037/oss/upload?ossType=1
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="professional.jpg"

< ../../images/fastdfs/professional.jpg
--WebAppBoundary--

### 阿里云 下载文件
### 阿里云下载指定 key 不需要加前缀 /
GET http://localhost:10037/oss/download?key=2020-06-21/云原生街.png&ossType=1&filePath=/Users/rexlin600/Desktop/2020-06-21/云原生街.png
Accept: application/json

########################################################################################

### 腾讯云 上传文件
POST http://localhost:10037/oss/upload?ossType=2
Content-Type: multipart/form-data; boundary=WebAppBoundary

--WebAppBoundary
Content-Disposition: form-data; name="file"; filename="professional.jpg"

< ../../images/fastdfs/professional.jpg
--WebAppBoundary--

### 腾讯云 下载文件
### 腾讯云下载指定 key 不需要加前缀 /
GET http://localhost:10037/oss/download?ossType=2&key=20190423/java.jpg&filePath=/Users/rexlin600/Desktop/20190423/java.jpg
Accept: application/json

