# For a quick start check out our HTTP Requests collection (Tools|HTTP Client|Open HTTP Requests Collection).
#
# Following HTTP Request Live Templates are available:
# * 'gtrp' and 'gtr' create a GET request with or without query parameters;
# * 'ptr' and 'ptrp' create a POST request with a simple or parameter-like body;
# * 'mptr' and 'fptr' create a POST request to submit a form with a text or file field (multipart/form-data);

### invoke direct method
POST http://localhost:10009/amqp/direct/invoke/directProductStr
Content-Type: application/json

### invoke fanout method
POST http://localhost:10009/amqp/fanout/invoke/fanoutProductStr
Content-Type: application/json

### invoke topic method
### 按照预期：queue.rexlin600.topic.a 和 queue.rexlin600.topic.all 队列会收到消息
POST http://localhost:10009/amqp/topic/invoke/topicProductStr1
Content-Type: application/json

### 按照预期：queue.rexlin600.topic.all 队列会收到消息
POST http://localhost:10009/amqp/topic/invoke/topicProductStr2
Content-Type: application/json

### 按照预期：queue.rexlin600.topic.all 队列会收到消息
POST http://localhost:10009/amqp/topic/invoke/topicProductStr3
Content-Type: application/json

### invoke simple method
POST http://localhost:10009/amqp/simple/invoke/simpleProductStr
Content-Type: application/json

### invoke work method
### 按照预期：消息会被均匀的消费
POST http://localhost:10009/amqp/work/invoke/workProductStr
Content-Type: application/json

### invoke dl method
### 按照预期：如果 DeadLetterConsumer 能够正常处理，则不会产生死信；反正注释 DeadLetterConsumer 则会产生死信，在消息发送10s后监听队列收到消息
POST http://localhost:10009/amqp/dl/invoke/productDlExpireStr
Content-Type: application/json

###


