### POST
POST http://localhost:10005/redis/set
Content-Type: application/json

{}

### GET
GET http://localhost:10005/redis/set/diff
Accept: application/json

### GET
GET http://localhost:10005/redis/set/intersect
Accept: application/json

### GET
GET http://localhost:10005/redis/set/union
Accept: application/json

### GET
GET http://localhost:10005/redis/set/member
Accept: application/json

### GET
GET http://localhost:10005/redis/set/pop
Accept: application/json

### GET
GET http://localhost:10005/redis/set/scan
Accept: application/json