### 测试HTTP请求 GET
GET http://localhost:10001/hello/get
Accept: application/json


### 测试HTTP请求 POST
POST http://localhost:10001/hello/post
Content-Type: application/json

{
  "name": "rexlin600",
  "age": 23
}


### 测试HTTP请求 PUT
PUT http://localhost:10001/hello/put/1
Content-Type: application/json


### 测试HTTP请求 DELETE
DELETE http://localhost:10001/hello/delete/2
Content-Type: application/json
